import { useEffect, useState } from "react";
import { getInvestmentRecommendation } from "../services/investmentService";

export default function InvestmentResult({ userData }) {
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function fetchResult() {
      try {
        const response = await getInvestmentRecommendation(userData);
        setResult(response);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    fetchResult();
  }, [userData]);

  if (loading) return <p>Generating your investment strategy...</p>;
  if (error) return <p>Error: {error}</p>;

  const ai = result.recommendation;

  return (
    <div className="investment-container">
      <h1>Your Investment Strategy</h1>
      <p className="risk-profile">Generated by AI • Risk Profile: Medium</p>

      <section className="card">
        <h2>Strategy Overview</h2>
        <p>{ai.summary}</p>

        <div className="highlight-box">
          <strong>ACTIONABLE STRATEGY</strong>
          <p>{ai.recommendation_text}</p>
        </div>
      </section>

      <section className="card">
        <h2>Risk Analysis</h2>
        <p>{ai.risk_analysis}</p>
      </section>

      <section className="card">
        <h2>Recommended Allocation</h2>
        <ul>
          <li>Equity: {ai.asset_allocation.equity}</li>
          <li>Debt: {ai.asset_allocation.debt}</li>
          <li>Alternatives: {ai.asset_allocation.alternatives}</li>
        </ul>
      </section>
    </div>
  );
}
