import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import { RecommendationResult } from '../types';

const Dashboard: React.FC = () => {
  const navigate = useNavigate();
  const [data, setData] = useState<RecommendationResult | null>(null);

  useEffect(() => {
    // Retrieve data passed from OTP page via LocalStorage
    const storedData = localStorage.getItem('ai_results');
    if (!storedData) {
      navigate('/advisor'); // Redirect if no data found
    } else {
      setData(JSON.parse(storedData));
    }
  }, [navigate]);

  if (!data) return <div className="p-10 text-center dark:text-white">Loading Dashboard...</div>;

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 pb-20 transition-colors duration-300">
      {/* Header */}
      <div className="bg-navy-900 dark:bg-slate-800 text-white pb-24 pt-12 px-4 rounded-b-[2rem] transition-colors duration-300">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center">
            <div>
              <h1 className="text-3xl font-bold">Your Investment Strategy</h1>
              <p className="text-slate-400 mt-1">Generated by AI • Risk Profile: <span className="text-emerald-400 font-semibold">{data.riskClassification}</span></p>
            </div>
            <div className="mt-4 md:mt-0 flex gap-3">
               <Button variant="secondary" onClick={() => alert('PDF Report sent to email!')}>
                 Email Report
               </Button>
               {data.pdfUrl && (
                 <a href={data.pdfUrl} target="_blank" rel="noreferrer">
                    <Button variant="outline" className="border-white text-white hover:bg-white hover:text-navy-900">
                      Download PDF
                    </Button>
                 </a>
               )}
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 -mt-16 space-y-8">
        
        {/* Top Cards Grid */}
        <div className="grid md:grid-cols-3 gap-6">
          <Card title="Strategy Overview" className="md:col-span-2">
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed text-lg">
              {data.explanation}
            </p>

            {/* Email Notification */}
            <div className="mt-4 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-800 rounded-lg flex items-start gap-3">
               <div className="text-blue-600 dark:text-blue-400 mt-0.5">
                 <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                   <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                   <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                 </svg>
               </div>
               <div>
                 <h4 className="text-sm font-semibold text-blue-900 dark:text-blue-100">Report Sent</h4>
                 <p className="text-sm text-blue-700 dark:text-blue-300 mt-0.5">
                   Your complete Recommendation PDF has been sent to your email. Please check your inbox.
                 </p>
               </div>
            </div>

            <div className="mt-4 p-4 bg-emerald-50 dark:bg-emerald-900/30 border border-emerald-100 dark:border-emerald-800 rounded-lg">
              <h4 className="font-bold text-emerald-800 dark:text-emerald-400 text-sm uppercase tracking-wide">Actionable Strategy</h4>
              <p className="text-emerald-700 dark:text-emerald-300 mt-1 font-medium">{data.strategy}</p>
            </div>
          </Card>

          <Card title="Market Opportunities">
            <ul className="space-y-3">
              {data.trendingAssets.map((asset, i) => (
                <li key={i} className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-700/50 rounded-lg">
                  <span className="font-medium text-slate-700 dark:text-slate-200">{asset}</span>
                  <span className="text-emerald-500 bg-emerald-100 dark:bg-emerald-900/50 px-2 py-0.5 rounded text-xs font-bold">Buy</span>
                </li>
              ))}
            </ul>
            <div className="mt-6">
               <h4 className="text-xs font-bold text-slate-400 uppercase mb-2">Key Risk Factor</h4>
               <p className="text-sm text-slate-600 dark:text-slate-300">{data.risksAndOpportunities}</p>
            </div>
          </Card>
        </div>

        {/* Portfolio Table */}
        <Card title="Recommended Allocation">
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="bg-slate-50 dark:bg-slate-700/50 border-b border-slate-100 dark:border-slate-700 text-xs uppercase text-slate-500 dark:text-slate-400 font-semibold">
                  <th className="px-6 py-4">Instrument Name</th>
                  <th className="px-6 py-4">Type</th>
                  <th className="px-6 py-4">Allocation (%)</th>
                  <th className="px-6 py-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                {data.instruments.map((item, idx) => (
                  <tr key={idx} className="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors">
                    <td className="px-6 py-4 font-medium text-navy-900 dark:text-white">{item.name}</td>
                    <td className="px-6 py-4 text-slate-500 dark:text-slate-400">{item.type}</td>
                    <td className="px-6 py-4">
                      <div className="flex items-center space-x-2">
                        <div className="w-24 h-2 bg-slate-200 dark:bg-slate-600 rounded-full overflow-hidden">
                          <div className="h-full bg-emerald-500" style={{ width: item.allocation }}></div>
                        </div>
                        <span className="text-sm font-bold text-navy-900 dark:text-white">{item.allocation}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <button className="text-emerald-600 hover:text-emerald-700 dark:text-emerald-400 dark:hover:text-emerald-300 text-sm font-semibold">Analyze</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        {/* Disclaimer */}
        <div className="text-center text-xs text-slate-400 max-w-2xl mx-auto">
          <p>Disclaimer: AI projections are based on historical data. Past performance is not indicative of future results. Consult a certified financial advisor before making large investments.</p>
        </div>

      </div>
    </div>
  );
};

export default Dashboard;